
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fatih
 */
public class AdminEkrani3 extends javax.swing.JFrame {
    
    MusicManager mm = new MusicManager();
    String ulke_ad,sanatci_ad;
    int sanatci_id;
    
    public void sanatciListeDoldur(){
        
        
        try {
            mm.preparedStatement=mm.con.prepareStatement("select * from sanatci");
            mm.rs=mm.preparedStatement.executeQuery();
            while(mm.rs.next()){
                sanatci_id=mm.rs.getInt("id");
                ulke_ad=mm.rs.getString("ulke_ad");
                sanatci_ad=mm.rs.getString("sanatci_ad");
                
                SanatciListeTextArea.setText(SanatciListeTextArea.getText()+sanatci_id+"    "+ulke_ad+"    "+sanatci_ad+"\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    public void sanatciEkle(){
        try {
            
            sanatci_ad=SNEsanatciadTextField.getText();
            ulke_ad=SNEsanatciulkeTextField.getText();
            
           
            mm.preparedStatement = mm.con.prepareStatement("select id\n"
                    + " from sanatci as o1 \n"
                    + " where id>all(select id from sanatci as o2\n"
                    + "						where o1.id<>o2.id);");
            mm.rs=mm.preparedStatement.executeQuery();
            while (mm.rs.next()) {
                sanatci_id = (mm.rs.getInt(1) + 1);
            }
            
            mm.preparedStatement=mm.con.prepareStatement("insert into sanatci(id,ulke_ad,sanatci_ad) values(?,?,?);");
            mm.preparedStatement.setInt(1, sanatci_id);
            mm.preparedStatement.setString(2, ulke_ad);
            mm.preparedStatement.setString(3, sanatci_ad);
            
            mm.preparedStatement.execute();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Hatalı Değer Girişi!");
        }
           
          
    }
    
     public void sanatciSil(){
        
        
        try {
            sanatci_id=Integer.parseInt(SNSsanatciidTextField.getText());
            mm.preparedStatement=mm.con.prepareStatement("delete from sanatci where id="+sanatci_id+";");
            mm.preparedStatement.execute();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Hatalı Değer Girişi!");
        }
        
    }

    /**
     * Creates new form AdminEkrani3
     */
    public AdminEkrani3() {
        initComponents();
        sanatciListeDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPanel3 = new javax.swing.JPanel();
        SNEPanel = new javax.swing.JPanel();
        SNEsanatciadLabel = new javax.swing.JLabel();
        SNEsanatciulkeLabel = new javax.swing.JLabel();
        SNEsanatciadTextField = new javax.swing.JTextField();
        SNEsanatciulkeTextField = new javax.swing.JTextField();
        SNEButton = new javax.swing.JButton();
        SNELabel = new javax.swing.JLabel();
        SNSPanel = new javax.swing.JPanel();
        SNSsanatciidLabel = new javax.swing.JLabel();
        SNSsanatciidTextField = new javax.swing.JTextField();
        SNSButton = new javax.swing.JButton();
        SNSLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SanatciListeTextArea = new javax.swing.JTextArea();
        AdminPanel3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(787, 570));

        AdminPanel3.setBackground(new java.awt.Color(142, 33, 33));
        AdminPanel3.setPreferredSize(new java.awt.Dimension(787, 570));

        SNEPanel.setBackground(new java.awt.Color(113, 19, 19));
        SNEPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        SNEsanatciadLabel.setText("sanatci ad");

        SNEsanatciulkeLabel.setText("sanatci ulke");

        SNEsanatciadTextField.setBackground(new java.awt.Color(113, 19, 19));
        SNEsanatciadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNEsanatciadTextFieldActionPerformed(evt);
            }
        });

        SNEsanatciulkeTextField.setBackground(new java.awt.Color(113, 19, 19));

        SNEButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SNEButton.setText("ekle");
        SNEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNEButtonActionPerformed(evt);
            }
        });

        SNELabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SNELabel.setText("sanatci ekle");

        javax.swing.GroupLayout SNEPanelLayout = new javax.swing.GroupLayout(SNEPanel);
        SNEPanel.setLayout(SNEPanelLayout);
        SNEPanelLayout.setHorizontalGroup(
            SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SNEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SNEPanelLayout.createSequentialGroup()
                        .addGroup(SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SNEPanelLayout.createSequentialGroup()
                                .addComponent(SNEsanatciadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SNEsanatciadTextField))
                            .addGroup(SNEPanelLayout.createSequentialGroup()
                                .addComponent(SNEsanatciulkeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SNEsanatciulkeTextField)))
                        .addContainerGap())
                    .addGroup(SNEPanelLayout.createSequentialGroup()
                        .addComponent(SNELabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SNEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        SNEPanelLayout.setVerticalGroup(
            SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SNEPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SNEsanatciadLabel)
                    .addComponent(SNEsanatciadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SNEsanatciulkeLabel)
                    .addComponent(SNEsanatciulkeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(SNEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SNEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNELabel))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        SNSPanel.setBackground(new java.awt.Color(200, 45, 45));
        SNSPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 29, 29), 4));

        SNSsanatciidLabel.setText("sanatci id");

        SNSsanatciidTextField.setBackground(new java.awt.Color(200, 45, 45));

        SNSButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SNSButton.setText("sil");
        SNSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNSButtonActionPerformed(evt);
            }
        });

        SNSLabel.setText("sanatci sil");

        javax.swing.GroupLayout SNSPanelLayout = new javax.swing.GroupLayout(SNSPanel);
        SNSPanel.setLayout(SNSPanelLayout);
        SNSPanelLayout.setHorizontalGroup(
            SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SNSPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SNSLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(SNSsanatciidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SNSPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SNSsanatciidTextField)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SNSPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(SNSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        SNSPanelLayout.setVerticalGroup(
            SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SNSPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SNSsanatciidLabel)
                    .addComponent(SNSsanatciidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(SNSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SNSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNSLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        SanatciListeTextArea.setEditable(false);
        SanatciListeTextArea.setBackground(new java.awt.Color(198, 63, 63));
        SanatciListeTextArea.setColumns(20);
        SanatciListeTextArea.setRows(5);
        SanatciListeTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));
        jScrollPane1.setViewportView(SanatciListeTextArea);

        AdminPanel3Button.setBackground(new java.awt.Color(102, 0, 0));
        AdminPanel3Button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AdminPanel3Button.setText(">>");
        AdminPanel3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        AdminPanel3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPanel3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanel3Layout = new javax.swing.GroupLayout(AdminPanel3);
        AdminPanel3.setLayout(AdminPanel3Layout);
        AdminPanel3Layout.setHorizontalGroup(
            AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SNSPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SNEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                        .addComponent(AdminPanel3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        AdminPanel3Layout.setVerticalGroup(
            AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SNEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SNSPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AdminPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminPanel3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SNEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNEButtonActionPerformed
        // TODO add your handling code here:
        SanatciListeTextArea.setText("");
        sanatciEkle();
        sanatciListeDoldur();
    }//GEN-LAST:event_SNEButtonActionPerformed

    private void SNEsanatciadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNEsanatciadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNEsanatciadTextFieldActionPerformed

    private void SNSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNSButtonActionPerformed
        // TODO add your handling code here:
        SanatciListeTextArea.setText("");
        sanatciSil();
        sanatciListeDoldur();
    }//GEN-LAST:event_SNSButtonActionPerformed

    private void AdminPanel3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPanel3ButtonActionPerformed
        // TODO add your handling code here:
        
        new AdminEkrani().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminPanel3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEkrani3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel3;
    private javax.swing.JButton AdminPanel3Button;
    private javax.swing.JButton SNEButton;
    private javax.swing.JLabel SNELabel;
    private javax.swing.JPanel SNEPanel;
    private javax.swing.JLabel SNEsanatciadLabel;
    private javax.swing.JTextField SNEsanatciadTextField;
    private javax.swing.JLabel SNEsanatciulkeLabel;
    private javax.swing.JTextField SNEsanatciulkeTextField;
    private javax.swing.JButton SNSButton;
    private javax.swing.JLabel SNSLabel;
    private javax.swing.JPanel SNSPanel;
    private javax.swing.JLabel SNSsanatciidLabel;
    private javax.swing.JTextField SNSsanatciidTextField;
    private javax.swing.JTextArea SanatciListeTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
