
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class GirisEkrani extends javax.swing.JFrame {
    MusicManager musicManager=new MusicManager();
    KayitEkrani kayitEkrani;
   

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        kullanici_adi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        kullanici_adi_icon = new javax.swing.JLabel();
        password_icon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        giris = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        kayit = new javax.swing.JLabel();
        cikis_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotify.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(64, 224, 208));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(64, 224, 208));
        password.setText("asdasdasd");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 210, 40));

        kullanici_adi.setBackground(new java.awt.Color(64, 224, 208));
        kullanici_adi.setForeground(new java.awt.Color(255, 255, 255));
        kullanici_adi.setText("Kullanıcı Adı");
        kullanici_adi.setBorder(null);
        kullanici_adi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kullanici_adiFocusGained(evt);
            }
        });
        jPanel3.add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 240, 40));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 250, 10));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 250, 10));

        kullanici_adi_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel3.add(kullanici_adi_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 30, 30));

        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N
        jPanel3.add(password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 30, 30));

        jPanel4.setBackground(new java.awt.Color(64, 224, 208));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        giris.setText("         Giriş");
        giris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giris, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giris, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, 30));

        jPanel5.setBackground(new java.awt.Color(64, 224, 208));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        kayit.setText("       Kaydol");
        kayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kayit, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kayit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 100, 30));

        cikis_icon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cikis_icon.setText("   X");
        cikis_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikis_iconMouseClicked(evt);
            }
        });
        jPanel3.add(cikis_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cikis_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikis_iconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cikis_iconMouseClicked

    private void kullanici_adiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kullanici_adiFocusGained
        kullanici_adi.setText("");
    }//GEN-LAST:event_kullanici_adiFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void girisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisMouseClicked
        String kullaniciAd=this.kullanici_adi.getText();
        String parola=new String(password.getPassword());
        String uyelik_tip_ad=null,ulke_ad=null; int kullanici_id=-1;
       boolean basariliMi= musicManager.girisYap(kullaniciAd, parola);
       if(basariliMi){
           
           //ana sayfaya geçişin sağlanması ve giriş yapan kullanıcının bilgilerinin ana sayfaya aktarılması
           
            try {
                
                musicManager.preparedStatement=musicManager.con.prepareStatement("select id,uyelik_tip_ad,ulke_ad\n"
                   + " from kullanici where kullanici_ad='"+kullaniciAd+"';");
           
           musicManager.rs=musicManager.preparedStatement.executeQuery();
            while (musicManager.rs.next()) {
               kullanici_id=musicManager.rs.getInt(1);
               uyelik_tip_ad=musicManager.rs.getString(2);
               ulke_ad=musicManager.rs.getString(3);
               
            }
            
                System.out.println(uyelik_tip_ad);
            if(uyelik_tip_ad.equals("admin")){
                AdminEkrani adminekrani = new AdminEkrani();
                adminekrani.setVisible(true);
            }else{
                AnaSayfa anasayfa;
                anasayfa = new AnaSayfa(kullanici_id,ulke_ad);
                anasayfa.kullanici_ad=kullaniciAd;
                anasayfa.uyelik_tip_ad=uyelik_tip_ad;
                
                
                anasayfa.setVisible(true);
            }
            
                
                
            } catch (SQLException ex) {
                Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           this.setVisible(false);
           
       }else{
           
           JOptionPane.showMessageDialog(this,"GİRİŞ BAŞARISIZ OLDU!");
       }
        
    }//GEN-LAST:event_girisMouseClicked

    private void kayitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitMouseClicked
        kayitEkrani=new KayitEkrani();
        kayitEkrani.setVisible(true);
        
    }//GEN-LAST:event_kayitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cikis_icon;
    private javax.swing.JLabel giris;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel kayit;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JLabel kullanici_adi_icon;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_icon;
    // End of variables declaration//GEN-END:variables
}
