
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KEREM-KARATAS
 */
public class KayitEkrani extends javax.swing.JFrame {
   MusicManager musicManager2=new MusicManager();
 
    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
       
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        r_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        r_kullanici_adi_icon = new javax.swing.JLabel();
        r_password_icon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        r_kayit = new javax.swing.JLabel();
        r_ulke_icon = new javax.swing.JLabel();
        r_ulke = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        r_email_icon = new javax.swing.JLabel();
        r_email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        r_uyelik_icon = new javax.swing.JLabel();
        r_uyelik = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        r_kullanici_adi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verify.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(186, 79, 84));
        jLabel5.setText("       R E G I S T E R");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r_password.setBackground(new java.awt.Color(186, 79, 84));
        r_password.setText("asdasdad");
        r_password.setBorder(null);
        r_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_passwordFocusGained(evt);
            }
        });
        jPanel3.add(r_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 230, 32));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 260, 10));

        r_kullanici_adi_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel3.add(r_kullanici_adi_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, 30));

        r_password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N
        jPanel3.add(r_password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 30, 30));

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        r_kayit.setText("         Kaydol");
        r_kayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_kayitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(r_kayit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(r_kayit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 120, 30));

        r_ulke_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/country.png"))); // NOI18N
        jPanel3.add(r_ulke_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 30, 30));

        r_ulke.setBackground(new java.awt.Color(186, 79, 84));
        r_ulke.setText("Ülke");
        r_ulke.setBorder(null);
        r_ulke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_ulkeFocusGained(evt);
            }
        });
        jPanel3.add(r_ulke, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 230, 32));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 260, 10));

        r_email_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel3.add(r_email_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 30, 30));

        r_email.setBackground(new java.awt.Color(186, 79, 84));
        r_email.setText("Email");
        r_email.setBorder(null);
        r_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_emailFocusGained(evt);
            }
        });
        jPanel3.add(r_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 230, 32));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 260, 10));

        r_uyelik_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uyelik.png"))); // NOI18N
        jPanel3.add(r_uyelik_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 30, 30));

        r_uyelik.setBackground(new java.awt.Color(186, 79, 84));
        r_uyelik.setText("Üyelik");
        r_uyelik.setBorder(null);
        r_uyelik.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_uyelikFocusGained(evt);
            }
        });
        jPanel3.add(r_uyelik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 230, 32));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 542, 260, 10));

        r_kullanici_adi.setBackground(new java.awt.Color(186, 79, 84));
        r_kullanici_adi.setText("Kullanıcı Adı");
        r_kullanici_adi.setBorder(null);
        r_kullanici_adi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_kullanici_adiFocusGained(evt);
            }
        });
        jPanel3.add(r_kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_passwordFocusGained
        r_password.setText("");
    }//GEN-LAST:event_r_passwordFocusGained

    private void r_kayitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_kayitMouseClicked
        String kullaniciAd =r_kullanici_adi.getText();
        String parola =new String(r_password.getPassword());
        String ulke =r_ulke.getText();
        String email=r_email.getText();
        String uyelikTip=r_uyelik.getText();
        int id=0;
        
       try {
           musicManager2.preparedStatement = musicManager2.con.prepareStatement("select id\n"
                   + " from kullanici as o1 \n"
                   + " where id>all(select id from kullanici as o2\n"
                   + "						where o1.id<>o2.id);");
           
           musicManager2.rs=musicManager2.preparedStatement.executeQuery();
            while (musicManager2.rs.next()) {
                id = (musicManager2.rs.getInt(1) + 1);
            }
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"hatalı giriş yaptınız!");
       }

           
        
        musicManager2.kullaniciEkle(this,id,kullaniciAd, parola, ulke, email, uyelikTip);
        
        
 
    }//GEN-LAST:event_r_kayitMouseClicked

    private void r_kullanici_adiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_kullanici_adiFocusGained
        r_kullanici_adi.setText("");
    }//GEN-LAST:event_r_kullanici_adiFocusGained

    private void r_ulkeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_ulkeFocusGained
        r_ulke.setText("");
    }//GEN-LAST:event_r_ulkeFocusGained

    private void r_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_emailFocusGained
       r_email.setText("");
    }//GEN-LAST:event_r_emailFocusGained

    private void r_uyelikFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_uyelikFocusGained
        r_uyelik.setText("");
    }//GEN-LAST:event_r_uyelikFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField r_email;
    private javax.swing.JLabel r_email_icon;
    private javax.swing.JLabel r_kayit;
    private javax.swing.JTextField r_kullanici_adi;
    private javax.swing.JLabel r_kullanici_adi_icon;
    private javax.swing.JPasswordField r_password;
    private javax.swing.JLabel r_password_icon;
    private javax.swing.JTextField r_ulke;
    private javax.swing.JLabel r_ulke_icon;
    private javax.swing.JTextField r_uyelik;
    private javax.swing.JLabel r_uyelik_icon;
    // End of variables declaration//GEN-END:variables
}
